class UserExistsError(Exception):
    """Пользователь уже существует."""
